### ISSUE TITLE
可以添加兼容symfony4的吗？

### ISSUE THREAD

**Issue by bhtomming** [askuiop/JimsEditorHubBundle#5]
在网上实在找不到合适的编辑器，老外做的都安装不了，看到你做的这个百度编辑器很高兴，但很遗憾不能在symfony4上安装。

**Comment by askuiop** [comment]
@bhtomming 可以的，只需要一点时间

**Comment by askuiop** [comment]
@bhtomming 已经兼容symfony4了

**Comment by bhtomming** [comment]
非常感谢作者的辛苦付出，symfony4的用法跟你旧的说明一样吗？
